[package]
name = "sketchbot"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1.3"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
winit = "0.29.10"

[[bin]]
name="recorder"
path="src/recorder.rs"
